Repository danestves/lite-embed, pull requests merged in 2022-04, with the labels that each got.

#57 feat: classes to style vue components
  packages/vue/src/components/aspect-ratio/aspect-ratio-item.vue
  packages/vue/src/components/aspect-ratio/aspect-ratio.vue
  packages/vue/src/components/vimeo-lite/vimeo-lite.vue
  packages/vue/src/components/youtube-lite/youtube-lite.vue
Labels: enhancement

#58 feat: umd targets for vue and utils
  packages/utils/package.json
  packages/utils/vite.config.ts
  packages/vue/vite.config.ts
Labels: enhancement

#60 docs: adding twitter meta tags
  website/theme.config.js
Labels: documentation, sync

#61 docs: adding fathom analytics
  website/package.json
  website/src/pages/_app.tsx
  website/tsconfig.json
  website/yarn.lock
Labels: documentation, enhancement

#62 docs: adding fathom analytics
  website/package.json
  website/src/pages/_app.tsx
  website/tsconfig.json
  website/yarn.lock
Labels: documentation, enhancement

#67 typo: doc's import
  website/src/pages/docs/react/quick-start.en.mdx
Labels: documentation

#68 typo: doc's import by @renejfc
  website/src/pages/docs/react/quick-start.en.mdx
Labels: documentation

#70 docs: create .all-contributorsrc [skip ci]
  .all-contributorsrc
  README.md
Labels: documentation

#71 chore: using `@lerna-lite` & `turbo` instead of `lerna` (not maintained)
  .github/workflows/release.yml
  .gitignore
  package.json
  packages/react/package.json
  packages/react/vite.config.ts
  packages/utils/package.json
  packages/utils/src/vite-env.d.ts
  packages/utils/tsconfig.json
  packages/utils/vite.config.ts
  packages/vue/package.json
  packages/vue/vite.config.ts
  turbo.json
  website/package.json
  website/yarn.lock
  yarn.lock
Labels: documentation

#72 fix: remove youtube gradient on loaded
  packages/react/src/components/youtube-lite/youtube-lite.tsx
  packages/vue/src/components/youtube-lite/youtube-lite.vue
Labels: bug

#74 docs: adding algolia search
  .github/workflows/release.yml
  .gitignore
  lerna.json
  package.json
  packages/react/package.json
  packages/react/src/components/youtube-lite/youtube-lite.tsx
  packages/react/vite.config.ts
  packages/utils/package.json
  packages/utils/src/vite-env.d.ts
  packages/utils/tsconfig.json
  packages/utils/vite.config.ts
  packages/vue/package.json
  packages/vue/src/components/youtube-lite/youtube-lite.vue
  packages/vue/vite.config.ts
  turbo.json
  website/package.json
  website/src/components/dosearch.tsx
  website/src/pages/_app.tsx
  website/src/pages/_document.tsx
  website/theme.config.js
  website/yarn.lock
  yarn.lock
Labels: documentation
